name: Go Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21' # 您的 Go 版本

      - name: Build
        run: go run build.go
        env:
          BUILD_ALL_PLATFORMS: true

      - name: List files in build directory
        run: ls -l ./build/

      # 添加压缩步骤
      - name: Compress Binaries
        run: |
          zip ./build/aes_for_Windows64.zip ./build/aes_for_Windows64.exe
          zip ./build/aes_for_Windows32.zip ./build/aes_for_Windows32.exe
          zip ./build/aes_for_macOS_AMD64.zip ./build/aes_for_macOS_AMD64
          zip ./build/aes_for_macOS_ARM64.zip ./build/aes_for_macOS_ARM64
          zip ./build/aes_for_Linux64.zip ./build/aes_for_Linux64
          zip ./build/aes_for_Linux32.zip ./build/aes_for_Linux32
          zip ./build/aes_for_Linux_ARM.zip ./build/aes_for_Linux_ARM

      # 添加上传步骤
      - name: Upload Compressed Windows 64-bit Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_Windows64.zip
          asset_name: aes_for_Windows64.zip
          asset_content_type: application/zip

      - name: Upload Compressed Windows 32-bit Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_Windows32.zip
          asset_name: aes_for_Windows32.zip
          asset_content_type: application/zip

      - name: Upload Compressed macOS AMD64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_macOS_AMD64.zip
          asset_name: aes_for_macOS_AMD64.zip
          asset_content_type: application/zip

      - name: Upload Compressed macOS ARM64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_macOS_ARM64.zip
          asset_name: aes_for_macOS_ARM64.zip
          asset_content_type: application/zip

      - name: Upload Compressed Linux 64-bit Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_Linux64.zip
          asset_name: aes_for_Linux64.zip
          asset_content_type: application/zip

      - name: Upload Compressed Linux 32-bit Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_Linux32.zip
          asset_name: aes_for_Linux32.zip
          asset_content_type: application/zip

      - name: Upload Compressed Linux ARM Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/aes_for_Linux_ARM.zip
          asset_name: aes_for_Linux_ARM.zip
          asset_content_type: application/zip
